### ISSUE TITLE
FAlign is not appearing in command pallet or acting on short-cut key

### ISSUE THREAD

**Issue by Frogli** [justbilt/sublime-fallign#1]
hejhej,

Just a moment ago I tried Align in Sublime Text 3 Build 3083, but I could not get it to work. I tried both the package control method installation as the git clone to the Sublime Package folder method. The Falign command is not showing up in the command pallet and also it does not act on the short cut cmd+\ when I pasted one of the examples in a empty Sublime Text window. Probably I am forgot something. I am using OS X el Capitan 10.11.1.

How can I fix this?

Thanks in advance for looking into this. This package looks very promising. I regularly run up the problem to manual align a list of variables.

**Comment by justbilt** [comment]
Thanks you feedback!

I have been tested it in Sublime Text 3 Build 3083 on OS X el Capitan, and it work's good! So i thank maybe the other package already used the shortcut `cmd+\`, the solution is typed `cmd + shift + p` and then open menu `Default (OSX).sublime-keymap - User`, setting you custome keymap binding:

```
[
    { "keys": ["super+\\"], "command": "falign" },
]
```

Buy the way, i add **command pallet support** in lastest commit , you could use `git pull` to get it, then typed `FAlign: Alignment` try it!

:-D

**Comment by Frogli** [comment]
Thanks for looking into this. I did a 'git pull' and applied the suggestion to the Default (OSX).sublime-keymap - User. Although this suggestion I applied by clicking in the menubar on 'Sublime Text > Preferences > Key bindings - User'. 

These result in that falign is available in the Command Pallet, but when activating it nothing happens. 
What I did was:
1. Type some variable definitions in a .java text file
2. Cmd + Shift + P
3. Type FAlign and hit the 'Enter' key.
Result: nothing changes.

Add. 3: I also changed the shortcut key Cmd+\ to the shortcut key Cmd+option+shift+p, but that did not work either. 

Attached some screenshots
- falign in the 'Package control: remove package' pallet (note that the description is not shown here and de title of the package is different the if it is installed via Package Control.
  ![screenshot 2015-11-18 09 56 08](https://cloud.githubusercontent.com/assets/1838688/11237741/f1a31964-8de1-11e5-8840-f983d6b93bf0.png)
- FAlign in the 'Command Pallet' 
  ![screenshot 2015-11-18 10 39 58](https://cloud.githubusercontent.com/assets/1838688/11237736/eabb8000-8de1-11e5-8c29-62e48afb10a3.png)
- The test file which I used to test FAlign Renamed the oil from JavaScratchPad.java to JavaScratchPad.txt, because of file type support restrictions here on github [JavaScratchPad.txt](https://github.com/justbilt/sublime-falign/files/37702/JavaScratchPad.txt)

Again thank you very much for looking into this.

grtz Henk

**Comment by Frogli** [comment]
Just discovered that the variables have to be in the right place. In my example above in the class. So I presume that it only works in programming lanuages like Java. Also I noticed that it only works in a certain context within a class. Eg if I have a Ruby class:

``` ruby
class SomeClass

  def initialize()
    @variable1name = ''
    @variable2 = ''

  end

  def readSettings
    begin
      @CONFIG  = 'configuration options'
      settingsRead = true
    rescue Psych::SyntaxError => exception
      settingsRead     = false
      anotherVariable = 10
    end
    return settingsRead
  end
end
```

In the file with this code I have to invoke FAlign three times right?
1. In the initialize method
2. In the readSettings method under the begin clause @CONFIG, settingsRead
3. In the readSettings method under the rescue clause.

I expected that FAlign would align the whole file, but maybe that would be a configurable feature request. I can not see the complications of this option yet. Anyways I am glad that is works!

**Comment by justbilt** [comment]
So sorry about that, i wrong thought that the user already knew how to use it.

the important step is :
**Put the cursor in the line that you want to align**

then push the shortcut !

it will find the lines before and after your selected that have same indent and similar keyword.

---

That's step is same as the other alignment plugin !  It's my mistake, i should explain it in readme file.

bilt

**Comment by Frogli** [comment]
No problem,

As a developer of a project you can get blind for certain things. I am glad we cleared this up.

Keep up de good work!

grtz Henk

**Comment by justbilt** [comment]
Thanks you feedback! :-D
